# Login
login:
  handler: ${self:custom.root}/auth/functions/login.handler
  events:
    - http:
        path: ${self:custom.apiPrefix}/auth/login
        method: post
        cors: true

# Register
register:
  handler: ${self:custom.root}/auth/functions/register.handler
  events:
    - http:
        path: ${self:custom.apiPrefix}/auth/register
        method: post
        cors: true

# Verify token
verify-token:
  handler: ${self:custom.root}/auth/functions/verify-token.handler
  events:
    - http:
        path: ${self:custom.apiPrefix}/auth/verify-token
        method: post
        cors: true
