# Get properties
get-properties:
  handler: ${self:custom.root}/property/functions/get-properties/get-properties.handler
  events:
    - http:
        path: ${self:custom.apiPrefix}/property
        method: get
        cors: true
        authorizer: authorize

# Get single property
get-single-property:
  handler: ${self:custom.root}/property/functions/get-single-property/get-single-property.handler
  events:
    - http:
        path: ${self:custom.apiPrefix}/property/{id}
        method: get
        cors: true
        authorizer: authorize
